# Generated by Django 6.0 on 2025-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mainapp_mes_lido_8b3ee1_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='mainapp_mes_data_en_ad9a47_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='mensagem',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='lido',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='data_envio',
            new_name='sent_at',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['read'], name='mainapp_mes_read_104d46_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-sent_at'], name='mainapp_mes_sent_at_1cfb81_idx'),
        ),
    ]
